style: logo has margin y:0.75rem on mobile
thepolicylab-projectportals/project-portal-theme pull request #537
Opened 2023-07-31 19:33 UTC by hetd54

NC before and after:

<img width="787" alt="nc-before" src="https://github.com/thepolicylab-projectportals/project-portal-theme/assets/35639529/fd06e4cb-14d4-458f-9c28-0d6c10cf8f02">
<img width="785" alt="nc-after" src="https://github.com/thepolicylab-projectportals/project-portal-theme/assets/35639529/c4677b65-6fe6-471f-8f53-0a281a7becc4">

Example Site before and after:

<img width="1167" alt="margin-before" src="https://github.com/thepolicylab-projectportals/project-portal-theme/assets/35639529/0e428438-fae9-4476-b647-bdb23a85969f">
<img width="1257" alt="margin-after" src="https://github.com/thepolicylab-projectportals/project-portal-theme/assets/35639529/385694ee-60d1-4adf-977d-37a95f9be27b">

2023-08-01 11:18 UTC, hollandjg requested changes
Hey Heather, thanks for looking at this! I've got a couple of tailwind suggestions to only change the spacing on mobile and keep the rest of the design the same.

2023-08-01 11:18 UTC, hollandjg commented on packages/gatsby-theme-project-portal/src/components/Navbar.tsx
> +              className="block mx-4 my-3 overflow-hidden text-nav text-black font-bold flex gap-4 items-center whitespace-nowrap"
to keep the old behavior for large screens, you could add 
```suggestion
              className="block mx-4 my-3 xl:my-auto overflow-hidden text-nav text-black font-bold flex gap-4 items-center whitespace-nowrap"
```

2023-08-01 11:18 UTC, hollandjg commented on packages/gatsby-theme-project-portal/src/components/Navbar.tsx
> +              className="block mx-4 my-3 overflow-hidden text-nav text-black font-bold flex gap-4 items-center whitespace-nowrap"
You might also need to edit line 88 to keep the position of the menu below the top bar:

Currently:
![Screenshot 2023-08-01 at 07 16 52](https://github.com/thepolicylab-projectportals/project-portal-theme/assets/2803227/05977105-0982-40ef-94da-38d0a81393d2)


With 5.5-rem set on line 88
```js
 <div className={"absolute top-[5.5rem]...
```
![Screenshot 2023-08-01 at 07 17 07](https://github.com/thepolicylab-projectportals/project-portal-theme/assets/2803227/3576b012-1437-431f-bc17-ff4c72d1c234)

2023-08-04 15:22 UTC, jashlu approved these changes
Look's great thanks!

2023-08-10 13:35 UTC, hollandjg approved these changes
Hey Heather, this looks great! It's blocked by #561 right now, so as soon as that is merged, this will be good to go. Thanks!

2023-08-10 13:35 UTC, merged